<?php

$wordlist = array(
    "quote",
    "voornaam",
    "bomen",
    "weer",
    "spiegel",
    "vliegtuig",
    "auto",
    "journalist",
    "kast",
    "bevrijdings",
    "beweging",
    "geensmiddel",
    "museum",
    "bank",
    "slapen",
    "website",
    "luidspreker",
    "eiland",
    "bovenbeen",
    "voetbal",
    "zuidpool",
    "anoniem",
    "paardenstal",
    "diameter",
    );
    ?>